version: '3.3'

services:
  api:
    build: .
    ports:
    - "3000:3000"
    command: npm run start:dev
    volumes:
    - .:/app
    links:
    - db
    environment: 
        DB_URI: "mongodb://db/munchkin"
  db:
    image: mongo:4-bionic
    ports:
        - 27017:27017
    volumes:
        - mongovol:/data/db
volumes:
  mongovol: